ARDUINO_DIR = /home/maximiliano/Trabajo/arduino
TARGET       = test
MCU          = atmega8
F_CPU        = 16000000
ARDUINO_PORT = /dev/ttyS0    
ARDUINO_LIBS =
AVR_TOOLS_PATH   = /usr/bin
AVRDUDE_CONF     = /etc/avrdude.conf              
include ./Arduino.mk


